version: '3.4'

services:

  #Database
  db:
    image: postgres
    restart: always
    
    environment:
      #User
      POSTGRES_USER: dnetcms
      #Database name
      POSTGRES_DB: DNetCMS
      #Password
      POSTGRES_PASSWORD: EhyZCF5Br

    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

    # ports:
    #   - 2500:5432


  #CMS itself
  dnetcms:
    image: wardef/dnetcms:develop
    restart: always
    
    # ports: 
    #   - 80:80
    
    deploy:
      mode: replicated
      replicas: 5
    
    environment: 
      ASPNETCORE_ENVIRONMENT: Production
      #ASPNETCORE_ENVIRONMENT: Development

    links: 
      - db
    depends_on:
      - db 
       
    volumes:
      - dnetdata:/app/Files
      - dnetdata:/app/Configurations
      - dnetdata:/app/Logs 



  #Web host
  hots:
    image: nginx
    restart: always

    depends_on: 
      - dnetcms

    deploy:
      placement:
        constraints:
          - node.role == manager

    #По хорошему надо бы свой образ, но так быстрее
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      
    ports: 
      - 80:80
      - 443:443
    links: 
      - dnetcms

volumes: 
  dnetdata: