version: '3'

services:

  #CMS itself
  dnetcms:
    image: wardef/dnetcms:develop
    restart: unless-stopped
    # ports: 
    #   - 5000:80
    links:
      - db

  #Database
  db:
    image: postgres
    restart: unless-stopped
    environment:
      #User
      POSTGRES_USER: dnetcms
      #Database name
      POSTGRES_DB: DNetCMS
      #Password
      POSTGRES_PASSWORD: EhyZCF5Br
      #Data location
      #PGDATA: /tmp/postgres

    volumes:
      - /home/wardef/postgres-data:/var/lib/postgresql/data

    # ports:
    #   - 2500:5432


  #Web host
  hots:
    image: nginx
    restart: always
    
    #По хорошему надо бы свой образ, но так быстрее
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf

    ports: 
      - 80:80
      - 443:443
    links: 
      - dnetcms