version: '3.2'

services:

  #CMS itself
  dnetcms:
    image: wardef/dnetcms:develop
    restart: unless-stopped
    # ports: 
    #   - 5000:80
    environment: 
      ASPNETCORE_ENVIRONMENT: Development

    # links:
    #   - db
    
    depends_on:
      - db  
    
    volumes:

      - dnetdata:/app/Files
      - dnetdata:/app/Configurations
      - dnetdata:/app/Logs 
      # - type: bind
      #   source: /docker/dnetcms/Files
      #   target: /app/Files
        
      # - type: bind
      #   source: /docker/dnetcms/Logs
      #   target: /app/Logs


  #Database
  db:
    image: postgres
    restart: unless-stopped
    environment:
      #User
      POSTGRES_USER: dnetcms
      #Database name
      POSTGRES_DB: DNetCMS
      #Password
      POSTGRES_PASSWORD: EhyZCF5Br
      #Data location
      #PGDATA: /tmp/postgres

    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

    # ports:
    #   - 2500:5432


  #Web host
  hots:
    image: nginx
    restart: always
    
    depends_on: 
      - dnetcms
      
    #По хорошему надо бы свой образ, но так быстрее
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf

    ports: 
      - 80:80
      - 443:443
    links: 
      - dnetcms

volumes: 
  dnetdata: